"""
After the preprocessor.py gave us clean, uniform images each (64 x 64) with 3 channels (RGB),
we now extract meaningful numbers from these images so the models can work with, converting the 64x64 images into a flat 1D array.

We exract two types of data:
  1. Color histogram: it is a distribution of colors in the image, which tells you how many pixels of each color are present in the image.

  2. HOG (Histogram of Oriented Gradients): Which captures the shape and structure of the objects in the image by looking at the gradients (change in pixel intensity across the image) in different directions. That gives the classifiers shape information.
"""

import pathlib
import pickle
import numpy as np
from skimage.feature import hog
from skimage import color
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

PREPROCESSED_DATA_PATH = pathlib.Path(__file__).parent / "preprocessed_data.pkl"
VECTORIZED_FEATURES_PATH = pathlib.Path(__file__).parent / "vector_features.pkl"


def load_preprocessed_images() -> tuple:
    """Load the preprocessed images inside preprocessed_data.pkl which is generated by preprocessor.py and is a dictionary with two keys: "images" and "labels"."""

    with open(PREPROCESSED_DATA_PATH, "rb") as f:
        data = pickle.load(f)

    print(f"Loaded preprocessed images and labels from {PREPROCESSED_DATA_PATH}")
    return data["images"], data["labels"]


def extract_color_histogram(image):
    color_histogram = []

    for channel in range(image.shape[2]):
        # Count how many pixels fall into each of the 32 brightness buckets for this channel
        histogram, _ = np.histogram(image[:, :, channel], bins=32, range=(0, 1))

        """
        [0.00 – 0.03125) 32
        [0.03125 – 0.0625) 12
        [0.0625 – 0.09375) 15
        ...
        [0.96875 – 1.0]
        """

        color_histogram.extend(histogram)

    return color_histogram


def extract_hog_features(image):
    """
    HOG looks for edges in the image by calculating changes in pixel intensity.
    For that the image needs to be in grayscale, becuase in a color image, red and blue color can both be edges and we wouldn't be able to tell.
    """
    gray_image = color.rgb2gray(image)

    features = hog(
        gray_image, orientations=9, pixels_per_cell=(8, 8), cells_per_block=(2, 2)
    )

    return features


def save_vector_features(features, labels):
    """
    We don't want to use all the images to train the model becuase then it would memorize every image and would be hard to generalize to new images (overfitting).

    So we split the data into a training set (80%) and a test set (20%) to evaluate the model's performance on UNSEEN data.
    """
    X_train, X_test, y_train, y_test = train_test_split(
        features, labels, test_size=0.2, random_state=42
    )

    scalar = StandardScaler()
    X_train_scaled = scalar.fit_transform(X_train)
    X_test_scaled = scalar.fit_transform(X_test)

    with open(VECTORIZED_FEATURES_PATH, "wb") as f:
        pickle.dump(
            {
                "X_train": X_train_scaled,
                "X_test": X_test_scaled,
                "y_train": y_train,
                "y_test": y_test,
            },
            f,
        )

    print(f"Saved vectorized features to {VECTORIZED_FEATURES_PATH}")


def extract_features():
    images, labels = load_preprocessed_images()

    feature_vector = []

    for image in images:
        color_histogram = extract_color_histogram(image)
        hog_features = extract_hog_features(image)

        combined = np.concatenate(
            [color_histogram, hog_features]
        )  # Append would put the lists next to each other giving a 2D array

        feature_vector.append(combined)

    print(f"Extracted features for {len(feature_vector)} images.")
    return np.array(feature_vector), labels


# Extract features and save them in a file
features, labels = extract_features()
save_vector_features(features, labels)
